### PR TITLE
Show absolute realm sizes in Studio

### PR DESCRIPTION
**Pull request by nirinchev**
WIP screenshot:

screenshot 2018-10-22 at 12 56 05

Depends on https://github.com/realm/realm-object-server-private/pull/1309 and https://github.com/realm/realm-sync/issues/2498

### CODE REVIEW

**Comment by kraenhansen** [comment]
@nirinchev would you care to include a screenshot in the description of the issue?

**Comment by kraenhansen** [comment]
Did you consider https://github.com/realm/realm-studio/issues/881 and what parts of this PR address which part of the issue? Or does it address a completely different issue? Which?

**Comment by kraenhansen** [comment]
Did you consider https://github.com/realm/realm-studio/issues/881 and what parts of this PR address which part of the issue? Or does it address a completely different issue? Which?

**Comment by nirinchev** [comment]
It addresses a different issue, which is exposing the absolute Realm file size as well as a button to force size recalculation. The motivation is that we've discovered that state size computations are quite expensive, so we'll reduce the frequency to once a day and we'll only compute Realms that are currently open at the time of computation. Exposing the file size is quite cheap though, so we'll do that and allow people to manually trigger a recomputation if that's what they want.

**Comment by nirinchev** [comment]
It addresses a different issue, which is exposing the absolute Realm file size as well as a button to force size recalculation. The motivation is that we've discovered that state size computations are quite expensive, so we'll reduce the frequency to once a day and we'll only compute Realms that are currently open at the time of computation. Exposing the file size is quite cheap though, so we'll do that and allow people to manually trigger a recomputation if that's what they want.

**Comment by nirinchev** [comment]
It addresses a different issue, which is exposing the absolute Realm file size as well as a button to force size recalculation. The motivation is that we've discovered that state size computations are quite expensive, so we'll reduce the frequency to once a day and we'll only compute Realms that are currently open at the time of computation. Exposing the file size is quite cheap though, so we'll do that and allow people to manually trigger a recomputation if that's what they want.

**Comment by nirinchev** [comment]
It addresses a different issue, which is exposing the absolute Realm file size as well as a button to force size recalculation. The motivation is that we've discovered that state size computations are quite expensive, so we'll reduce the frequency to once a day and we'll only compute Realms that are currently open at the time of computation. Exposing the file size is quite cheap though, so we'll do that and allow people to manually trigger a recomputation if that's what they want.

**Comment by nirinchev** [comment]
It addresses a different issue, which is exposing the absolute Realm file size as well as a button to force size recalculation. The motivation is that we've discovered that state size computations are quite expensive, so we'll reduce the frequency to once a day and we'll only compute Realms that are currently open at the time of computation. Exposing the file size is quite cheap though, so we'll do that and allow people to manually trigger a recomputation if that's what they want.

**Comment by nirinchev** [comment]
It addresses a different issue, which is exposing the absolute Realm file size as well as a button to force size recalculation. The motivation is that we've discovered that state size computations are quite expensive, so we'll reduce the frequency to once a day and we'll only compute Realms that are currently open at the time of computation. Exposing the file size is quite cheap though, so we'll do that and allow people to manually trigger a recomputation if that's what they want.

**Comment by nirinchev** [comment]
It addresses a different issue, which is exposing the absolute Realm file size as well as a button to force size recalculation. The motivation is that we've discovered that state size computations are quite expensive, so we'll reduce the frequency to once a day and we'll only compute Realms that are currently open at the time of computation. Exposing the file size is quite cheap though, so we'll do that and allow people to manually trigger a recomputation if that's what they want.

**Comment by nirinchev** [comment]
It addresses a different issue, which is exposing the absolute Realm file size as well as a button to force size recalculation. The motivation is that we've discovered that state size computations are quite expensive, so we'll reduce the frequency to once a day and we'll only compute Realms that are currently open at the time of computation. Exposing the file size is quite cheap though, so we'll do that and allow people to manually trigger a recomputation if that's what they want.

**Pull request merged**
